version: '3.7'

services:
  mtg-inventory-system:
    container_name: mtg-inventory-system
    build:
      context: .
      dockerfile: docker/inventory-system/Dockerfile
    volumes:
      - "./mtg_inventory_system/:/src/:delegated"
    ports:
      - "8000:8000"
    depends_on:
      - mtg-postgres

  mtg-postgres:
    container_name: mtg-postgres
    image: postgres:14.5-alpine
    restart: always
    env_file:
      - mtg_inventory_system/.env
    ports:
      - "5432:5432"

#  mtg-ai-card-detector:
#    container_name: mtg-card-detector
#    env_file:
#      - src/mtg_inventory_system/mtg_inventory_system/.env
#    build:
#      context: .
#      dockerfile: docker/mtg-card-detector/Dockerfile
#      target: mtg-card-detector
#    volumes:
#      - "./src/card_image_detector/:/src/:delegated"
