# Generated by Django 4.1.3 on 2023-02-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='collector_number',
            field=models.CharField(default='', max_length=10),
        ),
    ]
