# Generated by Django 4.1.3 on 2023-03-06 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_card_collector_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempCardNodeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('TRIGGERS', 'triggers'), ('SYNERGIZES_WITH', 'synergizes_with')], max_length=128)),
                ('connection_meta_data', models.JSONField(null=True)),
                ('votes_for', models.PositiveIntegerField(default=0)),
                ('total_votes', models.PositiveIntegerField(default=0)),
                ('dst_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_card_temp', to='common.card')),
                ('src_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_card_temp', to='common.card')),
            ],
        ),
        migrations.CreateModel(
            name='CardNodeConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('TRIGGERS', 'triggers'), ('SYNERGIZES_WITH', 'synergizes_with')], max_length=128)),
                ('connection_meta_data', models.JSONField(null=True)),
                ('dst_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dst_card', to='common.card')),
                ('src_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_card', to='common.card')),
            ],
        ),
    ]
